jobs:
  terraform:
    runs-on: ubuntu-latest

    env:
      AWS_REGION: eu-west-1
      TF_VAR_key_pair_name: ${{ secrets.TF_VAR_key_pair_name }}
      TF_VAR_allowed_ssh_cidr: ${{ secrets.TF_VAR_allowed_ssh_cidr }}
      TF_VAR_mongo_uri: ${{ secrets.TF_VAR_mongo_uri }}
      TF_VAR_jwt_secret_key: ${{ secrets.TF_VAR_jwt_secret_key }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        working-directory: terraform
        run: terraform init

      - name: Terraform Validate
        working-directory: terraform
        run: terraform validate

      - name: Terraform Plan
        working-directory: terraform
        run: terraform plan -input=false
